# Site settings
title: Instant Music
description: "Instant Music is the most convenient way to listen to the latest music on Chrome browser."
# baseurl: "instant-music/"
# url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
